### ISSUE TITLE
Pass env variables from existing secret to the blockscout-stack chart

### ISSUE THREAD

**Issue by air3ijai** [blockscout/helm-charts#18]
As for now, we have 2 ways to pass env variables to the [blockscout-stack](https://github.com/blockscout/helm-charts/tree/main/charts/blockscout-stack) chart
https://github.com/blockscout/helm-charts/blob/bbf43e41ce06c4b8cce0ce2711bfdef868bd9a4b/charts/blockscout-stack/values.yaml#L61-L66

It works well, but it also assume that if we would like to pass sensitive data to the chart, we should use something like
```yaml
  envFromSecret:
    DATABASE_URL: postgresql://postgres:sensitive-data@postgresql:5432/blockscout?ssl=false
    SECRET_KEY_BASE: sensitive-data
```
Which force us to store it in the values.yaml which usually stored in the repository. And in that case it would be usefully to have a way to pass data from existing secret, something like
```yaml
extraEnv:

  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: blockscout-secret
        key: DATABASE_URL

  - name: SECRET_KEY_BASE
    valueFrom:
      secretKeyRef:
        name: blockscout-secret
        key: SECRET_KEY_BASE
```

In that way, we can provision secrets in a secure way, outside of the values.yaml and than just reference in chart to them.

Code like following, may works in the [blockscout-deployment.yaml](https://github.com/blockscout/helm-charts/blob/main/charts/blockscout-stack/templates/blockscout-deployment.yaml#L44)
```yaml
          env:
            {{- range .Values.extraEnv }}
            - {{ toYaml . | nindent 14 | trim }}
            {{- end }}
```

Or we can use an existing approach as well
```yaml
envFrom:
  - secretRef:
      name: blockscout-secret
```
```yaml
          envFrom:
            - secretRef:
                name: {{ include "blockscout-stack.fullname" . }}-blockscout-env
            {{- range .Values.envFrom }}
            - {{ toYaml . | nindent 14 | trim }}
            {{- end }}
```
