### ISSUE TITLE
Add the ability to pass the non-literal env vars to the pods

### ISSUE THREAD

**Issue by MOZGIII** [blockscout/helm-charts#2]
I have a use case where my database is provided via an operator that creates secrets in the cluster. To construct a database URL I need to do the following:

```yaml
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-connection
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-connection
                  key: port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-connection
                  key: database
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)"
```

In the current Helm charts I can't set the `valueFrom` env var.
