### ISSUE TITLE
[blockscout-stack] migration job unable to use secret fail due to Helm hook pre-install

### ISSUE THREAD

**Issue by samclusker** [blockscout/helm-charts#66]
There is a cyclic dependency in the chart specifically with `blockscout-migration-job.yaml` whereby if you define an `envFromSecret` map including secrets, the migration job is unable to use them. This is due to the fact the Helm chart is not yet released and therefore neither are the secrets and so there is an issue with the Helm hooks lifecycle.

**Comment by nzenchik** [comment]
We know about this issue and think about better fix. For now workaround is to deploy with `separateApi.enabled: false` and enable it on second helm release.

**Comment by samclusker** [comment]
Okay thanks, just raising awareness. For now I've opted to deploy a secret with annotations that still tether it to the Helm release before releasing and it's assimilated. I also tried adding `hook-weight` but to no effect.

**Comment by ivel13** [comment]
Hi Blockscout team!
Any update here?

Just sharing my solution:
I ended up creating a separate secret (with the same data) specifically for the migration job:
```
...
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-env-temp
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
...
```
